name: Push release to Espressif Component Service

# If the commit is tagged, it will be uploaded. Other scenario silently fail.
on:
  push:
    tags:
      - v*

jobs:
  upload_components:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          submodules: "recursive"

      - name: Upload component to component registry
        uses: espressif/github-actions/upload_components@master
        with:
          name: "esp-libhelix-mp3"
          version: ${{ github.ref_name }}
          namespace: "chmorgan"
          api_token: ${{ secrets.ESP_IDF_COMPONENT_API_TOKEN }}
